# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: cloud/v1/githooks.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import cloud.v1.githooks_pb2 as cloud_dot_v1_dot_githooks__pb2


class InstallationsService(Protocol):
    async def list_installations(self, request: cloud_dot_v1_dot_githooks__pb2.ListInstallationsRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.ListInstallationsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_installation_by_i_d(self, request: cloud_dot_v1_dot_githooks__pb2.GetInstallationByIDRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.GetInstallationByIDResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def upsert_installation(self, request: cloud_dot_v1_dot_githooks__pb2.UpsertInstallationRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.UpsertInstallationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_installation(self, request: cloud_dot_v1_dot_githooks__pb2.DeleteInstallationRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.DeleteInstallationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class InstallationsServiceASGIApplication(ConnectASGIApplication[InstallationsService]):
    def __init__(self, service: InstallationsService | AsyncGenerator[InstallationsService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/cloud.v1.InstallationsService/ListInstallations": Endpoint.unary(
                    method=MethodInfo(
                        name="ListInstallations",
                        service_name="cloud.v1.InstallationsService",
                        input=cloud_dot_v1_dot_githooks__pb2.ListInstallationsRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.ListInstallationsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_installations,
                ),
                "/cloud.v1.InstallationsService/GetInstallationByID": Endpoint.unary(
                    method=MethodInfo(
                        name="GetInstallationByID",
                        service_name="cloud.v1.InstallationsService",
                        input=cloud_dot_v1_dot_githooks__pb2.GetInstallationByIDRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.GetInstallationByIDResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_installation_by_i_d,
                ),
                "/cloud.v1.InstallationsService/UpsertInstallation": Endpoint.unary(
                    method=MethodInfo(
                        name="UpsertInstallation",
                        service_name="cloud.v1.InstallationsService",
                        input=cloud_dot_v1_dot_githooks__pb2.UpsertInstallationRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.UpsertInstallationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.upsert_installation,
                ),
                "/cloud.v1.InstallationsService/DeleteInstallation": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteInstallation",
                        service_name="cloud.v1.InstallationsService",
                        input=cloud_dot_v1_dot_githooks__pb2.DeleteInstallationRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.DeleteInstallationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_installation,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/cloud.v1.InstallationsService"


class InstallationsServiceClient(ConnectClient):
    async def list_installations(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.ListInstallationsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.ListInstallationsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListInstallations",
                service_name="cloud.v1.InstallationsService",
                input=cloud_dot_v1_dot_githooks__pb2.ListInstallationsRequest,
                output=cloud_dot_v1_dot_githooks__pb2.ListInstallationsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_installation_by_i_d(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.GetInstallationByIDRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.GetInstallationByIDResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetInstallationByID",
                service_name="cloud.v1.InstallationsService",
                input=cloud_dot_v1_dot_githooks__pb2.GetInstallationByIDRequest,
                output=cloud_dot_v1_dot_githooks__pb2.GetInstallationByIDResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def upsert_installation(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.UpsertInstallationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.UpsertInstallationResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpsertInstallation",
                service_name="cloud.v1.InstallationsService",
                input=cloud_dot_v1_dot_githooks__pb2.UpsertInstallationRequest,
                output=cloud_dot_v1_dot_githooks__pb2.UpsertInstallationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_installation(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.DeleteInstallationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.DeleteInstallationResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteInstallation",
                service_name="cloud.v1.InstallationsService",
                input=cloud_dot_v1_dot_githooks__pb2.DeleteInstallationRequest,
                output=cloud_dot_v1_dot_githooks__pb2.DeleteInstallationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )



class NamespacesService(Protocol):
    async def list_namespaces(self, request: cloud_dot_v1_dot_githooks__pb2.ListNamespacesRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.ListNamespacesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def sync_namespaces(self, request: cloud_dot_v1_dot_githooks__pb2.SyncNamespacesRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.SyncNamespacesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_namespace_webhook(self, request: cloud_dot_v1_dot_githooks__pb2.GetNamespaceWebhookRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.GetNamespaceWebhookResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def set_namespace_webhook(self, request: cloud_dot_v1_dot_githooks__pb2.SetNamespaceWebhookRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.SetNamespaceWebhookResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class NamespacesServiceASGIApplication(ConnectASGIApplication[NamespacesService]):
    def __init__(self, service: NamespacesService | AsyncGenerator[NamespacesService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/cloud.v1.NamespacesService/ListNamespaces": Endpoint.unary(
                    method=MethodInfo(
                        name="ListNamespaces",
                        service_name="cloud.v1.NamespacesService",
                        input=cloud_dot_v1_dot_githooks__pb2.ListNamespacesRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.ListNamespacesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_namespaces,
                ),
                "/cloud.v1.NamespacesService/SyncNamespaces": Endpoint.unary(
                    method=MethodInfo(
                        name="SyncNamespaces",
                        service_name="cloud.v1.NamespacesService",
                        input=cloud_dot_v1_dot_githooks__pb2.SyncNamespacesRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.SyncNamespacesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.sync_namespaces,
                ),
                "/cloud.v1.NamespacesService/GetNamespaceWebhook": Endpoint.unary(
                    method=MethodInfo(
                        name="GetNamespaceWebhook",
                        service_name="cloud.v1.NamespacesService",
                        input=cloud_dot_v1_dot_githooks__pb2.GetNamespaceWebhookRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.GetNamespaceWebhookResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_namespace_webhook,
                ),
                "/cloud.v1.NamespacesService/SetNamespaceWebhook": Endpoint.unary(
                    method=MethodInfo(
                        name="SetNamespaceWebhook",
                        service_name="cloud.v1.NamespacesService",
                        input=cloud_dot_v1_dot_githooks__pb2.SetNamespaceWebhookRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.SetNamespaceWebhookResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.set_namespace_webhook,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/cloud.v1.NamespacesService"


class NamespacesServiceClient(ConnectClient):
    async def list_namespaces(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.ListNamespacesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.ListNamespacesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListNamespaces",
                service_name="cloud.v1.NamespacesService",
                input=cloud_dot_v1_dot_githooks__pb2.ListNamespacesRequest,
                output=cloud_dot_v1_dot_githooks__pb2.ListNamespacesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def sync_namespaces(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.SyncNamespacesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.SyncNamespacesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SyncNamespaces",
                service_name="cloud.v1.NamespacesService",
                input=cloud_dot_v1_dot_githooks__pb2.SyncNamespacesRequest,
                output=cloud_dot_v1_dot_githooks__pb2.SyncNamespacesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_namespace_webhook(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.GetNamespaceWebhookRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.GetNamespaceWebhookResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetNamespaceWebhook",
                service_name="cloud.v1.NamespacesService",
                input=cloud_dot_v1_dot_githooks__pb2.GetNamespaceWebhookRequest,
                output=cloud_dot_v1_dot_githooks__pb2.GetNamespaceWebhookResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def set_namespace_webhook(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.SetNamespaceWebhookRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.SetNamespaceWebhookResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SetNamespaceWebhook",
                service_name="cloud.v1.NamespacesService",
                input=cloud_dot_v1_dot_githooks__pb2.SetNamespaceWebhookRequest,
                output=cloud_dot_v1_dot_githooks__pb2.SetNamespaceWebhookResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )



class RulesService(Protocol):
    async def match_rules(self, request: cloud_dot_v1_dot_githooks__pb2.MatchRulesRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.MatchRulesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_rules(self, request: cloud_dot_v1_dot_githooks__pb2.ListRulesRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.ListRulesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_rule(self, request: cloud_dot_v1_dot_githooks__pb2.GetRuleRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.GetRuleResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def create_rule(self, request: cloud_dot_v1_dot_githooks__pb2.CreateRuleRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.CreateRuleResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def update_rule(self, request: cloud_dot_v1_dot_githooks__pb2.UpdateRuleRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.UpdateRuleResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_rule(self, request: cloud_dot_v1_dot_githooks__pb2.DeleteRuleRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.DeleteRuleResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class RulesServiceASGIApplication(ConnectASGIApplication[RulesService]):
    def __init__(self, service: RulesService | AsyncGenerator[RulesService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/cloud.v1.RulesService/MatchRules": Endpoint.unary(
                    method=MethodInfo(
                        name="MatchRules",
                        service_name="cloud.v1.RulesService",
                        input=cloud_dot_v1_dot_githooks__pb2.MatchRulesRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.MatchRulesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.match_rules,
                ),
                "/cloud.v1.RulesService/ListRules": Endpoint.unary(
                    method=MethodInfo(
                        name="ListRules",
                        service_name="cloud.v1.RulesService",
                        input=cloud_dot_v1_dot_githooks__pb2.ListRulesRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.ListRulesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_rules,
                ),
                "/cloud.v1.RulesService/GetRule": Endpoint.unary(
                    method=MethodInfo(
                        name="GetRule",
                        service_name="cloud.v1.RulesService",
                        input=cloud_dot_v1_dot_githooks__pb2.GetRuleRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.GetRuleResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_rule,
                ),
                "/cloud.v1.RulesService/CreateRule": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateRule",
                        service_name="cloud.v1.RulesService",
                        input=cloud_dot_v1_dot_githooks__pb2.CreateRuleRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.CreateRuleResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_rule,
                ),
                "/cloud.v1.RulesService/UpdateRule": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateRule",
                        service_name="cloud.v1.RulesService",
                        input=cloud_dot_v1_dot_githooks__pb2.UpdateRuleRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.UpdateRuleResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.update_rule,
                ),
                "/cloud.v1.RulesService/DeleteRule": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteRule",
                        service_name="cloud.v1.RulesService",
                        input=cloud_dot_v1_dot_githooks__pb2.DeleteRuleRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.DeleteRuleResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_rule,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/cloud.v1.RulesService"


class RulesServiceClient(ConnectClient):
    async def match_rules(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.MatchRulesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.MatchRulesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="MatchRules",
                service_name="cloud.v1.RulesService",
                input=cloud_dot_v1_dot_githooks__pb2.MatchRulesRequest,
                output=cloud_dot_v1_dot_githooks__pb2.MatchRulesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_rules(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.ListRulesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.ListRulesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListRules",
                service_name="cloud.v1.RulesService",
                input=cloud_dot_v1_dot_githooks__pb2.ListRulesRequest,
                output=cloud_dot_v1_dot_githooks__pb2.ListRulesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_rule(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.GetRuleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.GetRuleResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetRule",
                service_name="cloud.v1.RulesService",
                input=cloud_dot_v1_dot_githooks__pb2.GetRuleRequest,
                output=cloud_dot_v1_dot_githooks__pb2.GetRuleResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def create_rule(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.CreateRuleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.CreateRuleResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateRule",
                service_name="cloud.v1.RulesService",
                input=cloud_dot_v1_dot_githooks__pb2.CreateRuleRequest,
                output=cloud_dot_v1_dot_githooks__pb2.CreateRuleResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_rule(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.UpdateRuleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.UpdateRuleResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateRule",
                service_name="cloud.v1.RulesService",
                input=cloud_dot_v1_dot_githooks__pb2.UpdateRuleRequest,
                output=cloud_dot_v1_dot_githooks__pb2.UpdateRuleResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_rule(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.DeleteRuleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.DeleteRuleResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteRule",
                service_name="cloud.v1.RulesService",
                input=cloud_dot_v1_dot_githooks__pb2.DeleteRuleRequest,
                output=cloud_dot_v1_dot_githooks__pb2.DeleteRuleResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )



class DriversService(Protocol):
    async def list_drivers(self, request: cloud_dot_v1_dot_githooks__pb2.ListDriversRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.ListDriversResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_driver(self, request: cloud_dot_v1_dot_githooks__pb2.GetDriverRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.GetDriverResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def upsert_driver(self, request: cloud_dot_v1_dot_githooks__pb2.UpsertDriverRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.UpsertDriverResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_driver(self, request: cloud_dot_v1_dot_githooks__pb2.DeleteDriverRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.DeleteDriverResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class DriversServiceASGIApplication(ConnectASGIApplication[DriversService]):
    def __init__(self, service: DriversService | AsyncGenerator[DriversService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/cloud.v1.DriversService/ListDrivers": Endpoint.unary(
                    method=MethodInfo(
                        name="ListDrivers",
                        service_name="cloud.v1.DriversService",
                        input=cloud_dot_v1_dot_githooks__pb2.ListDriversRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.ListDriversResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_drivers,
                ),
                "/cloud.v1.DriversService/GetDriver": Endpoint.unary(
                    method=MethodInfo(
                        name="GetDriver",
                        service_name="cloud.v1.DriversService",
                        input=cloud_dot_v1_dot_githooks__pb2.GetDriverRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.GetDriverResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_driver,
                ),
                "/cloud.v1.DriversService/UpsertDriver": Endpoint.unary(
                    method=MethodInfo(
                        name="UpsertDriver",
                        service_name="cloud.v1.DriversService",
                        input=cloud_dot_v1_dot_githooks__pb2.UpsertDriverRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.UpsertDriverResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.upsert_driver,
                ),
                "/cloud.v1.DriversService/DeleteDriver": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteDriver",
                        service_name="cloud.v1.DriversService",
                        input=cloud_dot_v1_dot_githooks__pb2.DeleteDriverRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.DeleteDriverResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_driver,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/cloud.v1.DriversService"


class DriversServiceClient(ConnectClient):
    async def list_drivers(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.ListDriversRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.ListDriversResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListDrivers",
                service_name="cloud.v1.DriversService",
                input=cloud_dot_v1_dot_githooks__pb2.ListDriversRequest,
                output=cloud_dot_v1_dot_githooks__pb2.ListDriversResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_driver(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.GetDriverRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.GetDriverResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetDriver",
                service_name="cloud.v1.DriversService",
                input=cloud_dot_v1_dot_githooks__pb2.GetDriverRequest,
                output=cloud_dot_v1_dot_githooks__pb2.GetDriverResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def upsert_driver(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.UpsertDriverRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.UpsertDriverResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpsertDriver",
                service_name="cloud.v1.DriversService",
                input=cloud_dot_v1_dot_githooks__pb2.UpsertDriverRequest,
                output=cloud_dot_v1_dot_githooks__pb2.UpsertDriverResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_driver(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.DeleteDriverRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.DeleteDriverResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteDriver",
                service_name="cloud.v1.DriversService",
                input=cloud_dot_v1_dot_githooks__pb2.DeleteDriverRequest,
                output=cloud_dot_v1_dot_githooks__pb2.DeleteDriverResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )



class ProvidersService(Protocol):
    async def list_providers(self, request: cloud_dot_v1_dot_githooks__pb2.ListProvidersRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.ListProvidersResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_provider(self, request: cloud_dot_v1_dot_githooks__pb2.GetProviderRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.GetProviderResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def upsert_provider(self, request: cloud_dot_v1_dot_githooks__pb2.UpsertProviderRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.UpsertProviderResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_provider(self, request: cloud_dot_v1_dot_githooks__pb2.DeleteProviderRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.DeleteProviderResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class ProvidersServiceASGIApplication(ConnectASGIApplication[ProvidersService]):
    def __init__(self, service: ProvidersService | AsyncGenerator[ProvidersService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/cloud.v1.ProvidersService/ListProviders": Endpoint.unary(
                    method=MethodInfo(
                        name="ListProviders",
                        service_name="cloud.v1.ProvidersService",
                        input=cloud_dot_v1_dot_githooks__pb2.ListProvidersRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.ListProvidersResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_providers,
                ),
                "/cloud.v1.ProvidersService/GetProvider": Endpoint.unary(
                    method=MethodInfo(
                        name="GetProvider",
                        service_name="cloud.v1.ProvidersService",
                        input=cloud_dot_v1_dot_githooks__pb2.GetProviderRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.GetProviderResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_provider,
                ),
                "/cloud.v1.ProvidersService/UpsertProvider": Endpoint.unary(
                    method=MethodInfo(
                        name="UpsertProvider",
                        service_name="cloud.v1.ProvidersService",
                        input=cloud_dot_v1_dot_githooks__pb2.UpsertProviderRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.UpsertProviderResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.upsert_provider,
                ),
                "/cloud.v1.ProvidersService/DeleteProvider": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteProvider",
                        service_name="cloud.v1.ProvidersService",
                        input=cloud_dot_v1_dot_githooks__pb2.DeleteProviderRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.DeleteProviderResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_provider,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/cloud.v1.ProvidersService"


class ProvidersServiceClient(ConnectClient):
    async def list_providers(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.ListProvidersRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.ListProvidersResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListProviders",
                service_name="cloud.v1.ProvidersService",
                input=cloud_dot_v1_dot_githooks__pb2.ListProvidersRequest,
                output=cloud_dot_v1_dot_githooks__pb2.ListProvidersResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_provider(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.GetProviderRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.GetProviderResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetProvider",
                service_name="cloud.v1.ProvidersService",
                input=cloud_dot_v1_dot_githooks__pb2.GetProviderRequest,
                output=cloud_dot_v1_dot_githooks__pb2.GetProviderResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def upsert_provider(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.UpsertProviderRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.UpsertProviderResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpsertProvider",
                service_name="cloud.v1.ProvidersService",
                input=cloud_dot_v1_dot_githooks__pb2.UpsertProviderRequest,
                output=cloud_dot_v1_dot_githooks__pb2.UpsertProviderResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_provider(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.DeleteProviderRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.DeleteProviderResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteProvider",
                service_name="cloud.v1.ProvidersService",
                input=cloud_dot_v1_dot_githooks__pb2.DeleteProviderRequest,
                output=cloud_dot_v1_dot_githooks__pb2.DeleteProviderResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )



class SCMService(Protocol):
    async def get_s_c_m_client(self, request: cloud_dot_v1_dot_githooks__pb2.GetSCMClientRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.GetSCMClientResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class SCMServiceASGIApplication(ConnectASGIApplication[SCMService]):
    def __init__(self, service: SCMService | AsyncGenerator[SCMService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/cloud.v1.SCMService/GetSCMClient": Endpoint.unary(
                    method=MethodInfo(
                        name="GetSCMClient",
                        service_name="cloud.v1.SCMService",
                        input=cloud_dot_v1_dot_githooks__pb2.GetSCMClientRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.GetSCMClientResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_s_c_m_client,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/cloud.v1.SCMService"


class SCMServiceClient(ConnectClient):
    async def get_s_c_m_client(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.GetSCMClientRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.GetSCMClientResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetSCMClient",
                service_name="cloud.v1.SCMService",
                input=cloud_dot_v1_dot_githooks__pb2.GetSCMClientRequest,
                output=cloud_dot_v1_dot_githooks__pb2.GetSCMClientResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )



class EventLogsService(Protocol):
    async def list_event_logs(self, request: cloud_dot_v1_dot_githooks__pb2.ListEventLogsRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.ListEventLogsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_event_log_analytics(self, request: cloud_dot_v1_dot_githooks__pb2.GetEventLogAnalyticsRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.GetEventLogAnalyticsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_event_log_timeseries(self, request: cloud_dot_v1_dot_githooks__pb2.GetEventLogTimeseriesRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.GetEventLogTimeseriesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_event_log_breakdown(self, request: cloud_dot_v1_dot_githooks__pb2.GetEventLogBreakdownRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.GetEventLogBreakdownResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def update_event_log_status(self, request: cloud_dot_v1_dot_githooks__pb2.UpdateEventLogStatusRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.UpdateEventLogStatusResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class EventLogsServiceASGIApplication(ConnectASGIApplication[EventLogsService]):
    def __init__(self, service: EventLogsService | AsyncGenerator[EventLogsService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/cloud.v1.EventLogsService/ListEventLogs": Endpoint.unary(
                    method=MethodInfo(
                        name="ListEventLogs",
                        service_name="cloud.v1.EventLogsService",
                        input=cloud_dot_v1_dot_githooks__pb2.ListEventLogsRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.ListEventLogsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_event_logs,
                ),
                "/cloud.v1.EventLogsService/GetEventLogAnalytics": Endpoint.unary(
                    method=MethodInfo(
                        name="GetEventLogAnalytics",
                        service_name="cloud.v1.EventLogsService",
                        input=cloud_dot_v1_dot_githooks__pb2.GetEventLogAnalyticsRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.GetEventLogAnalyticsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_event_log_analytics,
                ),
                "/cloud.v1.EventLogsService/GetEventLogTimeseries": Endpoint.unary(
                    method=MethodInfo(
                        name="GetEventLogTimeseries",
                        service_name="cloud.v1.EventLogsService",
                        input=cloud_dot_v1_dot_githooks__pb2.GetEventLogTimeseriesRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.GetEventLogTimeseriesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_event_log_timeseries,
                ),
                "/cloud.v1.EventLogsService/GetEventLogBreakdown": Endpoint.unary(
                    method=MethodInfo(
                        name="GetEventLogBreakdown",
                        service_name="cloud.v1.EventLogsService",
                        input=cloud_dot_v1_dot_githooks__pb2.GetEventLogBreakdownRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.GetEventLogBreakdownResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_event_log_breakdown,
                ),
                "/cloud.v1.EventLogsService/UpdateEventLogStatus": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateEventLogStatus",
                        service_name="cloud.v1.EventLogsService",
                        input=cloud_dot_v1_dot_githooks__pb2.UpdateEventLogStatusRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.UpdateEventLogStatusResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.update_event_log_status,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/cloud.v1.EventLogsService"


class EventLogsServiceClient(ConnectClient):
    async def list_event_logs(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.ListEventLogsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.ListEventLogsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListEventLogs",
                service_name="cloud.v1.EventLogsService",
                input=cloud_dot_v1_dot_githooks__pb2.ListEventLogsRequest,
                output=cloud_dot_v1_dot_githooks__pb2.ListEventLogsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_event_log_analytics(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.GetEventLogAnalyticsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.GetEventLogAnalyticsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetEventLogAnalytics",
                service_name="cloud.v1.EventLogsService",
                input=cloud_dot_v1_dot_githooks__pb2.GetEventLogAnalyticsRequest,
                output=cloud_dot_v1_dot_githooks__pb2.GetEventLogAnalyticsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_event_log_timeseries(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.GetEventLogTimeseriesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.GetEventLogTimeseriesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetEventLogTimeseries",
                service_name="cloud.v1.EventLogsService",
                input=cloud_dot_v1_dot_githooks__pb2.GetEventLogTimeseriesRequest,
                output=cloud_dot_v1_dot_githooks__pb2.GetEventLogTimeseriesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_event_log_breakdown(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.GetEventLogBreakdownRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.GetEventLogBreakdownResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetEventLogBreakdown",
                service_name="cloud.v1.EventLogsService",
                input=cloud_dot_v1_dot_githooks__pb2.GetEventLogBreakdownRequest,
                output=cloud_dot_v1_dot_githooks__pb2.GetEventLogBreakdownResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_event_log_status(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.UpdateEventLogStatusRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.UpdateEventLogStatusResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateEventLogStatus",
                service_name="cloud.v1.EventLogsService",
                input=cloud_dot_v1_dot_githooks__pb2.UpdateEventLogStatusRequest,
                output=cloud_dot_v1_dot_githooks__pb2.UpdateEventLogStatusResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class InstallationsServiceSync(Protocol):
    def list_installations(self, request: cloud_dot_v1_dot_githooks__pb2.ListInstallationsRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.ListInstallationsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_installation_by_i_d(self, request: cloud_dot_v1_dot_githooks__pb2.GetInstallationByIDRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.GetInstallationByIDResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def upsert_installation(self, request: cloud_dot_v1_dot_githooks__pb2.UpsertInstallationRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.UpsertInstallationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_installation(self, request: cloud_dot_v1_dot_githooks__pb2.DeleteInstallationRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.DeleteInstallationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class InstallationsServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: InstallationsServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/cloud.v1.InstallationsService/ListInstallations": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListInstallations",
                        service_name="cloud.v1.InstallationsService",
                        input=cloud_dot_v1_dot_githooks__pb2.ListInstallationsRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.ListInstallationsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_installations,
                ),
                "/cloud.v1.InstallationsService/GetInstallationByID": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetInstallationByID",
                        service_name="cloud.v1.InstallationsService",
                        input=cloud_dot_v1_dot_githooks__pb2.GetInstallationByIDRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.GetInstallationByIDResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_installation_by_i_d,
                ),
                "/cloud.v1.InstallationsService/UpsertInstallation": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpsertInstallation",
                        service_name="cloud.v1.InstallationsService",
                        input=cloud_dot_v1_dot_githooks__pb2.UpsertInstallationRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.UpsertInstallationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.upsert_installation,
                ),
                "/cloud.v1.InstallationsService/DeleteInstallation": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteInstallation",
                        service_name="cloud.v1.InstallationsService",
                        input=cloud_dot_v1_dot_githooks__pb2.DeleteInstallationRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.DeleteInstallationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_installation,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/cloud.v1.InstallationsService"


class InstallationsServiceClientSync(ConnectClientSync):
    def list_installations(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.ListInstallationsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.ListInstallationsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListInstallations",
                service_name="cloud.v1.InstallationsService",
                input=cloud_dot_v1_dot_githooks__pb2.ListInstallationsRequest,
                output=cloud_dot_v1_dot_githooks__pb2.ListInstallationsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_installation_by_i_d(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.GetInstallationByIDRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.GetInstallationByIDResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetInstallationByID",
                service_name="cloud.v1.InstallationsService",
                input=cloud_dot_v1_dot_githooks__pb2.GetInstallationByIDRequest,
                output=cloud_dot_v1_dot_githooks__pb2.GetInstallationByIDResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def upsert_installation(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.UpsertInstallationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.UpsertInstallationResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpsertInstallation",
                service_name="cloud.v1.InstallationsService",
                input=cloud_dot_v1_dot_githooks__pb2.UpsertInstallationRequest,
                output=cloud_dot_v1_dot_githooks__pb2.UpsertInstallationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_installation(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.DeleteInstallationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.DeleteInstallationResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteInstallation",
                service_name="cloud.v1.InstallationsService",
                input=cloud_dot_v1_dot_githooks__pb2.DeleteInstallationRequest,
                output=cloud_dot_v1_dot_githooks__pb2.DeleteInstallationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class NamespacesServiceSync(Protocol):
    def list_namespaces(self, request: cloud_dot_v1_dot_githooks__pb2.ListNamespacesRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.ListNamespacesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def sync_namespaces(self, request: cloud_dot_v1_dot_githooks__pb2.SyncNamespacesRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.SyncNamespacesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_namespace_webhook(self, request: cloud_dot_v1_dot_githooks__pb2.GetNamespaceWebhookRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.GetNamespaceWebhookResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def set_namespace_webhook(self, request: cloud_dot_v1_dot_githooks__pb2.SetNamespaceWebhookRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.SetNamespaceWebhookResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class NamespacesServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: NamespacesServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/cloud.v1.NamespacesService/ListNamespaces": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListNamespaces",
                        service_name="cloud.v1.NamespacesService",
                        input=cloud_dot_v1_dot_githooks__pb2.ListNamespacesRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.ListNamespacesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_namespaces,
                ),
                "/cloud.v1.NamespacesService/SyncNamespaces": EndpointSync.unary(
                    method=MethodInfo(
                        name="SyncNamespaces",
                        service_name="cloud.v1.NamespacesService",
                        input=cloud_dot_v1_dot_githooks__pb2.SyncNamespacesRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.SyncNamespacesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.sync_namespaces,
                ),
                "/cloud.v1.NamespacesService/GetNamespaceWebhook": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetNamespaceWebhook",
                        service_name="cloud.v1.NamespacesService",
                        input=cloud_dot_v1_dot_githooks__pb2.GetNamespaceWebhookRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.GetNamespaceWebhookResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_namespace_webhook,
                ),
                "/cloud.v1.NamespacesService/SetNamespaceWebhook": EndpointSync.unary(
                    method=MethodInfo(
                        name="SetNamespaceWebhook",
                        service_name="cloud.v1.NamespacesService",
                        input=cloud_dot_v1_dot_githooks__pb2.SetNamespaceWebhookRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.SetNamespaceWebhookResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.set_namespace_webhook,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/cloud.v1.NamespacesService"


class NamespacesServiceClientSync(ConnectClientSync):
    def list_namespaces(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.ListNamespacesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.ListNamespacesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListNamespaces",
                service_name="cloud.v1.NamespacesService",
                input=cloud_dot_v1_dot_githooks__pb2.ListNamespacesRequest,
                output=cloud_dot_v1_dot_githooks__pb2.ListNamespacesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def sync_namespaces(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.SyncNamespacesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.SyncNamespacesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SyncNamespaces",
                service_name="cloud.v1.NamespacesService",
                input=cloud_dot_v1_dot_githooks__pb2.SyncNamespacesRequest,
                output=cloud_dot_v1_dot_githooks__pb2.SyncNamespacesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_namespace_webhook(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.GetNamespaceWebhookRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.GetNamespaceWebhookResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetNamespaceWebhook",
                service_name="cloud.v1.NamespacesService",
                input=cloud_dot_v1_dot_githooks__pb2.GetNamespaceWebhookRequest,
                output=cloud_dot_v1_dot_githooks__pb2.GetNamespaceWebhookResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def set_namespace_webhook(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.SetNamespaceWebhookRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.SetNamespaceWebhookResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SetNamespaceWebhook",
                service_name="cloud.v1.NamespacesService",
                input=cloud_dot_v1_dot_githooks__pb2.SetNamespaceWebhookRequest,
                output=cloud_dot_v1_dot_githooks__pb2.SetNamespaceWebhookResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class RulesServiceSync(Protocol):
    def match_rules(self, request: cloud_dot_v1_dot_githooks__pb2.MatchRulesRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.MatchRulesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_rules(self, request: cloud_dot_v1_dot_githooks__pb2.ListRulesRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.ListRulesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_rule(self, request: cloud_dot_v1_dot_githooks__pb2.GetRuleRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.GetRuleResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def create_rule(self, request: cloud_dot_v1_dot_githooks__pb2.CreateRuleRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.CreateRuleResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def update_rule(self, request: cloud_dot_v1_dot_githooks__pb2.UpdateRuleRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.UpdateRuleResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_rule(self, request: cloud_dot_v1_dot_githooks__pb2.DeleteRuleRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.DeleteRuleResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class RulesServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: RulesServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/cloud.v1.RulesService/MatchRules": EndpointSync.unary(
                    method=MethodInfo(
                        name="MatchRules",
                        service_name="cloud.v1.RulesService",
                        input=cloud_dot_v1_dot_githooks__pb2.MatchRulesRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.MatchRulesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.match_rules,
                ),
                "/cloud.v1.RulesService/ListRules": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListRules",
                        service_name="cloud.v1.RulesService",
                        input=cloud_dot_v1_dot_githooks__pb2.ListRulesRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.ListRulesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_rules,
                ),
                "/cloud.v1.RulesService/GetRule": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetRule",
                        service_name="cloud.v1.RulesService",
                        input=cloud_dot_v1_dot_githooks__pb2.GetRuleRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.GetRuleResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_rule,
                ),
                "/cloud.v1.RulesService/CreateRule": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateRule",
                        service_name="cloud.v1.RulesService",
                        input=cloud_dot_v1_dot_githooks__pb2.CreateRuleRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.CreateRuleResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_rule,
                ),
                "/cloud.v1.RulesService/UpdateRule": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateRule",
                        service_name="cloud.v1.RulesService",
                        input=cloud_dot_v1_dot_githooks__pb2.UpdateRuleRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.UpdateRuleResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_rule,
                ),
                "/cloud.v1.RulesService/DeleteRule": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteRule",
                        service_name="cloud.v1.RulesService",
                        input=cloud_dot_v1_dot_githooks__pb2.DeleteRuleRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.DeleteRuleResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_rule,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/cloud.v1.RulesService"


class RulesServiceClientSync(ConnectClientSync):
    def match_rules(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.MatchRulesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.MatchRulesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="MatchRules",
                service_name="cloud.v1.RulesService",
                input=cloud_dot_v1_dot_githooks__pb2.MatchRulesRequest,
                output=cloud_dot_v1_dot_githooks__pb2.MatchRulesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_rules(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.ListRulesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.ListRulesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListRules",
                service_name="cloud.v1.RulesService",
                input=cloud_dot_v1_dot_githooks__pb2.ListRulesRequest,
                output=cloud_dot_v1_dot_githooks__pb2.ListRulesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_rule(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.GetRuleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.GetRuleResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetRule",
                service_name="cloud.v1.RulesService",
                input=cloud_dot_v1_dot_githooks__pb2.GetRuleRequest,
                output=cloud_dot_v1_dot_githooks__pb2.GetRuleResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def create_rule(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.CreateRuleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.CreateRuleResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateRule",
                service_name="cloud.v1.RulesService",
                input=cloud_dot_v1_dot_githooks__pb2.CreateRuleRequest,
                output=cloud_dot_v1_dot_githooks__pb2.CreateRuleResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update_rule(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.UpdateRuleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.UpdateRuleResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateRule",
                service_name="cloud.v1.RulesService",
                input=cloud_dot_v1_dot_githooks__pb2.UpdateRuleRequest,
                output=cloud_dot_v1_dot_githooks__pb2.UpdateRuleResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_rule(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.DeleteRuleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.DeleteRuleResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteRule",
                service_name="cloud.v1.RulesService",
                input=cloud_dot_v1_dot_githooks__pb2.DeleteRuleRequest,
                output=cloud_dot_v1_dot_githooks__pb2.DeleteRuleResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class DriversServiceSync(Protocol):
    def list_drivers(self, request: cloud_dot_v1_dot_githooks__pb2.ListDriversRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.ListDriversResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_driver(self, request: cloud_dot_v1_dot_githooks__pb2.GetDriverRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.GetDriverResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def upsert_driver(self, request: cloud_dot_v1_dot_githooks__pb2.UpsertDriverRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.UpsertDriverResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_driver(self, request: cloud_dot_v1_dot_githooks__pb2.DeleteDriverRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.DeleteDriverResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class DriversServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: DriversServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/cloud.v1.DriversService/ListDrivers": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListDrivers",
                        service_name="cloud.v1.DriversService",
                        input=cloud_dot_v1_dot_githooks__pb2.ListDriversRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.ListDriversResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_drivers,
                ),
                "/cloud.v1.DriversService/GetDriver": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetDriver",
                        service_name="cloud.v1.DriversService",
                        input=cloud_dot_v1_dot_githooks__pb2.GetDriverRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.GetDriverResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_driver,
                ),
                "/cloud.v1.DriversService/UpsertDriver": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpsertDriver",
                        service_name="cloud.v1.DriversService",
                        input=cloud_dot_v1_dot_githooks__pb2.UpsertDriverRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.UpsertDriverResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.upsert_driver,
                ),
                "/cloud.v1.DriversService/DeleteDriver": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteDriver",
                        service_name="cloud.v1.DriversService",
                        input=cloud_dot_v1_dot_githooks__pb2.DeleteDriverRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.DeleteDriverResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_driver,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/cloud.v1.DriversService"


class DriversServiceClientSync(ConnectClientSync):
    def list_drivers(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.ListDriversRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.ListDriversResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListDrivers",
                service_name="cloud.v1.DriversService",
                input=cloud_dot_v1_dot_githooks__pb2.ListDriversRequest,
                output=cloud_dot_v1_dot_githooks__pb2.ListDriversResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_driver(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.GetDriverRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.GetDriverResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetDriver",
                service_name="cloud.v1.DriversService",
                input=cloud_dot_v1_dot_githooks__pb2.GetDriverRequest,
                output=cloud_dot_v1_dot_githooks__pb2.GetDriverResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def upsert_driver(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.UpsertDriverRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.UpsertDriverResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpsertDriver",
                service_name="cloud.v1.DriversService",
                input=cloud_dot_v1_dot_githooks__pb2.UpsertDriverRequest,
                output=cloud_dot_v1_dot_githooks__pb2.UpsertDriverResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_driver(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.DeleteDriverRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.DeleteDriverResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteDriver",
                service_name="cloud.v1.DriversService",
                input=cloud_dot_v1_dot_githooks__pb2.DeleteDriverRequest,
                output=cloud_dot_v1_dot_githooks__pb2.DeleteDriverResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class ProvidersServiceSync(Protocol):
    def list_providers(self, request: cloud_dot_v1_dot_githooks__pb2.ListProvidersRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.ListProvidersResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_provider(self, request: cloud_dot_v1_dot_githooks__pb2.GetProviderRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.GetProviderResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def upsert_provider(self, request: cloud_dot_v1_dot_githooks__pb2.UpsertProviderRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.UpsertProviderResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_provider(self, request: cloud_dot_v1_dot_githooks__pb2.DeleteProviderRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.DeleteProviderResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class ProvidersServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: ProvidersServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/cloud.v1.ProvidersService/ListProviders": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListProviders",
                        service_name="cloud.v1.ProvidersService",
                        input=cloud_dot_v1_dot_githooks__pb2.ListProvidersRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.ListProvidersResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_providers,
                ),
                "/cloud.v1.ProvidersService/GetProvider": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetProvider",
                        service_name="cloud.v1.ProvidersService",
                        input=cloud_dot_v1_dot_githooks__pb2.GetProviderRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.GetProviderResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_provider,
                ),
                "/cloud.v1.ProvidersService/UpsertProvider": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpsertProvider",
                        service_name="cloud.v1.ProvidersService",
                        input=cloud_dot_v1_dot_githooks__pb2.UpsertProviderRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.UpsertProviderResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.upsert_provider,
                ),
                "/cloud.v1.ProvidersService/DeleteProvider": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteProvider",
                        service_name="cloud.v1.ProvidersService",
                        input=cloud_dot_v1_dot_githooks__pb2.DeleteProviderRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.DeleteProviderResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_provider,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/cloud.v1.ProvidersService"


class ProvidersServiceClientSync(ConnectClientSync):
    def list_providers(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.ListProvidersRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.ListProvidersResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListProviders",
                service_name="cloud.v1.ProvidersService",
                input=cloud_dot_v1_dot_githooks__pb2.ListProvidersRequest,
                output=cloud_dot_v1_dot_githooks__pb2.ListProvidersResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_provider(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.GetProviderRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.GetProviderResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetProvider",
                service_name="cloud.v1.ProvidersService",
                input=cloud_dot_v1_dot_githooks__pb2.GetProviderRequest,
                output=cloud_dot_v1_dot_githooks__pb2.GetProviderResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def upsert_provider(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.UpsertProviderRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.UpsertProviderResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpsertProvider",
                service_name="cloud.v1.ProvidersService",
                input=cloud_dot_v1_dot_githooks__pb2.UpsertProviderRequest,
                output=cloud_dot_v1_dot_githooks__pb2.UpsertProviderResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_provider(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.DeleteProviderRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.DeleteProviderResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteProvider",
                service_name="cloud.v1.ProvidersService",
                input=cloud_dot_v1_dot_githooks__pb2.DeleteProviderRequest,
                output=cloud_dot_v1_dot_githooks__pb2.DeleteProviderResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class SCMServiceSync(Protocol):
    def get_s_c_m_client(self, request: cloud_dot_v1_dot_githooks__pb2.GetSCMClientRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.GetSCMClientResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class SCMServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: SCMServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/cloud.v1.SCMService/GetSCMClient": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetSCMClient",
                        service_name="cloud.v1.SCMService",
                        input=cloud_dot_v1_dot_githooks__pb2.GetSCMClientRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.GetSCMClientResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_s_c_m_client,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/cloud.v1.SCMService"


class SCMServiceClientSync(ConnectClientSync):
    def get_s_c_m_client(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.GetSCMClientRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.GetSCMClientResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetSCMClient",
                service_name="cloud.v1.SCMService",
                input=cloud_dot_v1_dot_githooks__pb2.GetSCMClientRequest,
                output=cloud_dot_v1_dot_githooks__pb2.GetSCMClientResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class EventLogsServiceSync(Protocol):
    def list_event_logs(self, request: cloud_dot_v1_dot_githooks__pb2.ListEventLogsRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.ListEventLogsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_event_log_analytics(self, request: cloud_dot_v1_dot_githooks__pb2.GetEventLogAnalyticsRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.GetEventLogAnalyticsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_event_log_timeseries(self, request: cloud_dot_v1_dot_githooks__pb2.GetEventLogTimeseriesRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.GetEventLogTimeseriesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_event_log_breakdown(self, request: cloud_dot_v1_dot_githooks__pb2.GetEventLogBreakdownRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.GetEventLogBreakdownResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def update_event_log_status(self, request: cloud_dot_v1_dot_githooks__pb2.UpdateEventLogStatusRequest, ctx: RequestContext) -> cloud_dot_v1_dot_githooks__pb2.UpdateEventLogStatusResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class EventLogsServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: EventLogsServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None) -> None:
        super().__init__(
            endpoints={
                "/cloud.v1.EventLogsService/ListEventLogs": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListEventLogs",
                        service_name="cloud.v1.EventLogsService",
                        input=cloud_dot_v1_dot_githooks__pb2.ListEventLogsRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.ListEventLogsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_event_logs,
                ),
                "/cloud.v1.EventLogsService/GetEventLogAnalytics": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetEventLogAnalytics",
                        service_name="cloud.v1.EventLogsService",
                        input=cloud_dot_v1_dot_githooks__pb2.GetEventLogAnalyticsRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.GetEventLogAnalyticsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_event_log_analytics,
                ),
                "/cloud.v1.EventLogsService/GetEventLogTimeseries": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetEventLogTimeseries",
                        service_name="cloud.v1.EventLogsService",
                        input=cloud_dot_v1_dot_githooks__pb2.GetEventLogTimeseriesRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.GetEventLogTimeseriesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_event_log_timeseries,
                ),
                "/cloud.v1.EventLogsService/GetEventLogBreakdown": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetEventLogBreakdown",
                        service_name="cloud.v1.EventLogsService",
                        input=cloud_dot_v1_dot_githooks__pb2.GetEventLogBreakdownRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.GetEventLogBreakdownResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_event_log_breakdown,
                ),
                "/cloud.v1.EventLogsService/UpdateEventLogStatus": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateEventLogStatus",
                        service_name="cloud.v1.EventLogsService",
                        input=cloud_dot_v1_dot_githooks__pb2.UpdateEventLogStatusRequest,
                        output=cloud_dot_v1_dot_githooks__pb2.UpdateEventLogStatusResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_event_log_status,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/cloud.v1.EventLogsService"


class EventLogsServiceClientSync(ConnectClientSync):
    def list_event_logs(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.ListEventLogsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.ListEventLogsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListEventLogs",
                service_name="cloud.v1.EventLogsService",
                input=cloud_dot_v1_dot_githooks__pb2.ListEventLogsRequest,
                output=cloud_dot_v1_dot_githooks__pb2.ListEventLogsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_event_log_analytics(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.GetEventLogAnalyticsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.GetEventLogAnalyticsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetEventLogAnalytics",
                service_name="cloud.v1.EventLogsService",
                input=cloud_dot_v1_dot_githooks__pb2.GetEventLogAnalyticsRequest,
                output=cloud_dot_v1_dot_githooks__pb2.GetEventLogAnalyticsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_event_log_timeseries(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.GetEventLogTimeseriesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.GetEventLogTimeseriesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetEventLogTimeseries",
                service_name="cloud.v1.EventLogsService",
                input=cloud_dot_v1_dot_githooks__pb2.GetEventLogTimeseriesRequest,
                output=cloud_dot_v1_dot_githooks__pb2.GetEventLogTimeseriesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_event_log_breakdown(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.GetEventLogBreakdownRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.GetEventLogBreakdownResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetEventLogBreakdown",
                service_name="cloud.v1.EventLogsService",
                input=cloud_dot_v1_dot_githooks__pb2.GetEventLogBreakdownRequest,
                output=cloud_dot_v1_dot_githooks__pb2.GetEventLogBreakdownResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update_event_log_status(
        self,
        request: cloud_dot_v1_dot_githooks__pb2.UpdateEventLogStatusRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> cloud_dot_v1_dot_githooks__pb2.UpdateEventLogStatusResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateEventLogStatus",
                service_name="cloud.v1.EventLogsService",
                input=cloud_dot_v1_dot_githooks__pb2.UpdateEventLogStatusRequest,
                output=cloud_dot_v1_dot_githooks__pb2.UpdateEventLogStatusResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
